[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "wezterm"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
vergen = "3"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.1"

[dependencies]
base91 = { path = "base91" }
bitflags = "1.0"
boxfnonce = "0.1"
clipboard = "0.5"
dirs = "1.0"
euclid = "0.19"
failure = "0.1"
failure_derive = "0.1"
foreign-types = "0.3"
freetype = { path = "deps/freetype" }
gl = "0.11"
glium = { version = "0.23", default-features = false, features = ["glutin", "icon_loading"]}
harfbuzz = { path = "deps/harfbuzz" }
lazy_static = "1.3"
leb128 = "0.2"
libc = "0.2"
open = "1.2"
palette = "0.4"
promise = { path = "promise" }
rayon = "1.0"
serde = {version="1.0", features = ["rc"]}
serde_derive = "1.0"
structopt = "0.2"
term = { path = "term" }
termwiz = { path = "termwiz"}
toml = "0.4"
unicode-normalization = "0.1"
unicode-width = "0.1"
varbincode = { path = "varbincode" }
winit = "0.18"
zstd = "0.4"

[target.'cfg(unix)'.dependencies]
mio = "0.6"
mio-extras = "2.0"

[dependencies.fontconfig]
optional = true
path = "deps/fontconfig"

# on linux, font-loader pulls in servo-font* crates which conflict with
# our newer font related deps, so we avoid it on linux
[target.'cfg(any(windows, target_os = "macos"))'.dependencies]
font-loader = { version = "0.8" }

[target."cfg(windows)".dependencies]
shared_library = "0.1"
uds_windows = "0.1"
winapi = { version = "0.3", features = [
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
]}

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
egli = "0.4"
fontconfig = { path = "deps/fontconfig" }
x11 = {version ="2.18", features = ["xlib_xcb"]}


[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
xcb = "0.8"
xcb-util = { features = [ "icccm", "ewmh", "keysyms", ], version = "0.2" }
xkbcommon = { version = "0.4", features = ["x11"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
cocoa = "0.18"
core-foundation = "0.6"
core-graphics = "0.17"
core-text = "13.1"

[features]
debug-escape-sequences = ["term/debug-escape-sequences"]
force-glutin = []
force-fontconfig = ["fontconfig"]

[patch.crates-io]
# We need https://github.com/tomaka/glutin/pull/1099
glutin = { git = "https://github.com/yvt/glutin", branch="patch-macos-iscurrent" }
# This allows using the git tab in the help output
structopt-derive = { git = "https://github.com/wez/structopt", branch="vergen" }
# For some macOS bindings https://github.com/servo/core-foundation-rs/pull/315
cocoa = { git = "https://github.com/fanzeyi/core-foundation-rs", branch="add-nsbundle" }
core-foundation = { git = "https://github.com/fanzeyi/core-foundation-rs", branch="add-nsbundle" }
core-graphics = { git = "https://github.com/fanzeyi/core-foundation-rs", branch="add-nsbundle" }
core-text = { git = "https://github.com/fanzeyi/core-foundation-rs", branch="add-nsbundle" }

[workspace]

[profile.release]
debug = true
